# Generated by Django 4.2.8 on 2025-11-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=0, max_digits=12)),
                ('reference', models.CharField(db_column='Reference', max_length=200)),
                ('transfer_screenshot', models.CharField(blank=True, db_column='TransferScreenshot', max_length=512, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED'), ('REJECTED', 'REJECTED')], db_column='Status', default='PENDING', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, db_column='VerifiedAt', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('booking', models.OneToOneField(db_column='BookingId', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.bookings')),
                ('verified_by', models.ForeignKey(blank=True, db_column='VerifiedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to='accounts.users')),
            ],
            options={
                'verbose_name': 'Payments',
                'verbose_name_plural': 'Payments',
                'db_table': 'Payments',
                'managed': True,
                'indexes': [models.Index(fields=['reference'], name='idx_payment_reference'), models.Index(fields=['status'], name='idx_payment_status')],
            },
        ),
    ]
