# Generated by Django 4.2.8 on 2025-11-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên sân')),
                ('price_per_hour', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá theo giờ')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Tạm dừng')], default='active', max_length=10, verbose_name='Tình trạng')),
            ],
        ),
    ]
