# Generated by Django 4.2.8 on 2025-11-02 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=120)),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('image_url', models.CharField(blank=True, db_column='ImageUrl', max_length=512, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('price_per_hour', models.DecimalField(db_column='PricePerHour', decimal_places=0, max_digits=12)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
            ],
            options={
                'verbose_name_plural': 'Courts',
                'db_table': 'Courts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Courtclosures',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_column='StartTime')),
                ('end_time', models.DateTimeField(db_column='EndTime')),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=255, null=True)),
                ('court', models.ForeignKey(db_column='CourtId', on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='courts.courts')),
            ],
            options={
                'db_table': 'CourtClosures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Courtphotos',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('image_url', models.CharField(db_column='ImageUrl', max_length=512)),
                ('caption', models.CharField(blank=True, db_column='Caption', max_length=255, null=True)),
                ('sort_order', models.IntegerField(db_column='SortOrder', default=0)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('court', models.ForeignKey(db_column='CourtId', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='courts.courts')),
            ],
            options={
                'db_table': 'CourtPhotos',
                'managed': True,
                'unique_together': {('court', 'sort_order')},
            },
        ),
    ]
