# Generated by Django 5.2.7 on 2025-11-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_hour', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Tạm dừng')], default='active', max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='courtphotos',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='courtphotos',
            name='court',
        ),
        migrations.DeleteModel(
            name='Courtclosures',
        ),
        migrations.DeleteModel(
            name='Courtphotos',
        ),
    ]
