# Generated by Django 5.2.7 on 2025-11-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookings_court'),
        ('courts', '0002_court_alter_courtphotos_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courts',
        ),
    ]
