# Generated by Django 4.2.8 on 2025-11-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('full_name', models.CharField(blank=True, db_column='FullName', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True, unique=True)),
                ('role', models.CharField(db_column='Role', default='User', max_length=10)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
            ],
            options={
                'verbose_name': 'Accounts',
                'verbose_name_plural': 'Accounts',
                'db_table': 'Accounts',
                'managed': True,
            },
        ),
    ]
