# Generated by Django 4.2.8 on 2025-11-02 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_column='StartTime')),
                ('end_time', models.DateTimeField(db_column='EndTime')),
                ('hours', models.DecimalField(db_column='Hours', decimal_places=2, max_digits=4)),
                ('price_per_hour_snapshot', models.DecimalField(db_column='PricePerHourSnapshot', decimal_places=0, max_digits=12)),
                ('total_amount', models.DecimalField(db_column='TotalAmount', decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED')], db_column='Status', default='PENDING', max_length=10)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('court', models.ForeignKey(db_column='CourtId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='courts.courts')),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.users')),
            ],
            options={
                'verbose_name': 'Bookings',
                'verbose_name_plural': 'Bookings',
                'db_table': 'Bookings',
                'managed': True,
                'indexes': [models.Index(fields=['court', 'start_time'], name='idx_booking_court_time'), models.Index(fields=['user', 'start_time'], name='idx_booking_user_time')],
            },
        ),
    ]
