# Generated by Django 5.2.7 on 2025-11-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('courts', '0002_court_alter_courtphotos_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='court',
            field=models.ForeignKey(db_column='CourtId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='courts.court'),
        ),
    ]
